version: '3.8'

services:
  postgresql:
    image: postgres
    container_name: sauna-backend
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin
    restart: always
  